<template>
    <div class="container">
        <div class="container-gradient"></div>
        <div>
            <h1>Roberto Alcázar</h1>
            <h2 class="regular">Software Developer • <span class="slide-in-top">{{ current_epithet }}</span></h2>
            <h2 class="mobile">Software Developer<br/>•<br/><span class="slide-in-top">{{ current_epithet }}</span></h2>
        </div>
        
    </div>
</template>

<script>
export default {
    data() {
        return {
            epithets: [
                "Human being",
                "Miserable little pile of secrets",
                "Junk food enthusiast",
                "The Simpsons maniac",
                "Video game enjoyer",
                "JRPG fan",
                "Mexican",
                "Robbie",
                "Regular guy"
            ],
            epithet_history: [],
            current_epithet: ""
        }
    },
    methods: {
        changeEpithet() {
            if (this.epithets.length == 0) {
                this.epithets = [...this.epithet_history]
                this.epithet_history = []
            }

            let random_index = Math.floor(Math.random() * this.epithets.length)
            this.current_epithet = this.epithets.splice(random_index, 1)[0]
            this.epithet_history.push(this.current_epithet)
        }
    },
    mounted() {
        this.changeEpithet()
        setInterval(() => {
            this.changeEpithet()
        }, 3000)
    }
}
</script>

<style scoped>
.container {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    min-height: 100vh;

    background-color: #f3f3f3;
    background-image:  repeating-linear-gradient(45deg, #f3f3f3 25%, transparent 25%, transparent 75%, #f3f3f3 75%, #f3f3f3), repeating-linear-gradient(45deg, #f3f3f3 25%, #fefefe 25%, #fefefe 75%, #f3f3f3 75%, #f3f3f3);
    background-position: 0 0, 40px 40px;
    background-size: 80px 80px;
    animation: pattern 5s linear infinite;

    background-attachment: fixed;
}

.container-gradient{
    /* background: linear-gradient(180deg, transparent, #a6aaad); */
    background: linear-gradient(180deg, transparent, #8eafe4);
    width: 100%;
    height: 100vh;
    position: absolute;
    /* opacity: 25%; */
}

.container h1 {
    flex: 1 1 100%;
    text-align: center;
    font-weight: 900;
    font-size: 4em;
}

h2.regular{
    display: none;
}

h2.mobile{
    text-align: center;
}

@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }

    50% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }
}

@keyframes pattern {
    from {
        background-position: 0 0, 40px 40px;
    }

    to {
        background-position: -80px -80px, -40px -40px;
    }
}

@media (min-width: 1024px) {
    .container {
        min-height: 100vh;
    }

    .container-gradient{
        height: 100vh;
        /* opacity: 25%; */
    }

    h2.mobile{
        display: none;
    }

    h2.regular{
        display: block;
        text-align: center;
    }
}

.slide-in-top {
    -webkit-animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-10-31 23:22:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
    0% {
        -webkit-transform: translateY(-1000px);
        transform: translateY(-1000px);
        opacity: 0;
    }

    100% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
}

@keyframes slide-in-top {
    0% {
        -webkit-transform: translateY(-1000px);
        transform: translateY(-1000px);
        opacity: 0;
    }

    100% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
}
</style>